Traceback (most recent call last):
  File "/lunarc/nobackup/projects/lu2023-17-41/carl/LTU/LTU_Thesis_v2/cdnet/train_cdnet_BSHBD_80-10-10_400.py", line 154, in <module>
    main()
  File "/lunarc/nobackup/projects/lu2023-17-41/carl/LTU/LTU_Thesis_v2/cdnet/train_cdnet_BSHBD_80-10-10_400.py", line 123, in main
    update_yaml_path(data_yaml, dataset_path, train_path, val_path, test_path)
  File "/lunarc/nobackup/projects/lu2023-17-41/carl/LTU/LTU_Thesis_v2/cdnet/train_cdnet_BSHBD_80-10-10_400.py", line 29, in update_yaml_path
    with open(yaml_file, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/lunarc/nobackup/projects/lu2023-17-41/carl/LTU/LTU_Thesis_v2/cdnet/cdnet_cdnet_BSHBD_80-10-10-page_400/data.yaml'
